import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const configPath = path.join(projectRoot, 'config.json');

const defaults = {
  ownerUsername: 'ModVinny',
  botUsername: 'tj',
  friendlyPlayers: ['ModVinny'],
  host: '127.0.0.1',
  port: 25565,
  minecraftVersion: '1.21.11',
  auth: 'offline',
  llmProvider: 'ollama',
  ollamaUrl: 'http://127.0.0.1:11434',
  // LLM: code-first companion. 'dialogue' = chat flavor only; 'off' = no Ollama; 'full' = fuzzy commands too.
  llmMode: 'dialogue',
  llmEnabled: true,
  ollamaModel: 'gemma2-2b-local:latest',
  models: {
    default: 'gemma2-2b-local:latest',
    commandRouter: 'gemma2-2b-local:latest',
    planner: 'gemma2-2b-local:latest',
    dialogue: 'gemma2-2b-local:latest',
    codingStructured: 'gemma2-2b-local:latest',
    codingHeavy: 'gemma2-2b-local:latest',
    fastFallback: 'gemma2-2b-local:latest',
    legacyFallback: 'gemma2-2b-local:latest'
  },
  modelOptions: {
    default: { temperature: 0, stream: false, think: false, timeoutMs: 20000, numPredict: 100 },
    commandRouter: { temperature: 0, stream: false, think: false, timeoutMs: 20000, numPredict: 100 },
    planner: { temperature: 0, stream: false, think: false, timeoutMs: 20000, numPredict: 100 },
    dialogue: { temperature: 0.7, stream: false, think: false, timeoutMs: 25000, numPredict: 120 },
    codingStructured: { temperature: 0, stream: false, think: false, timeoutMs: 20000, numPredict: 100 },
    codingHeavy: { temperature: 0, stream: false, think: false, timeoutMs: 20000, numPredict: 100 },
    fastFallback: { temperature: 0.4, stream: false, think: false, timeoutMs: 15000, numPredict: 80 },
    legacyFallback: { temperature: 0, stream: false, think: false, timeoutMs: 15000, numPredict: 80 }
  },
  // Surface digs: never swim for sand/clay/gravel/dirt unless you set allowUnderwaterDigging true.
  allowUnderwaterDigging: false,
  minOxygenToDig: 12,
  // Base pathfinder cost for water/lava (higher = avoid more). Surface digs use ~10000 temporarily.
  defaultLiquidCost: 80,
  // Surface coal / early mining: allow without a full torch stack (charcoal path first).
  allowMiningWithoutTorches: false,
  minTorchCountForMining: 4,
  // Keep logs/planks for crafting when smelting (fuel prefers coal/charcoal first).
  smeltReserveLogs: 4,
  smeltReservePlanks: 4,
  competentCoreEnabled: true,
  competentCoreMode: 'helper',
  competentCorePreferDeterministicMacros: true,
  competentCoreAllowOnlySafeMacros: true,
  competentCoreUseLlmOnlyForIntent: true,
  // Longer so progress_to_iron can finish; macros can also set timeoutMs.
  competentCoreMaxActiveTaskMs: 600000,
  competentCoreMaxRetries: 2,
  competentCoreAskOnFailure: true,
  competentCoreReportShort: true,
  competentCoreDisableAdvancedAutonomy: true,
  allowFallbackWithoutPlugin: false,
  loadOptionalMineflayerPlugins: true,
  thinCoreEnabled: true,
  // Kit stays on for owner testing (chat "tj kit" also force-applies).
  starterKitEnabled: true,
  starterKitOnSpawn: false,
  starterKitOncePerSession: true,
  // Progression testing: force kit off and enable surface ore scouting.
  progressionTestMode: false,
  surfaceOreScoutEnabled: true,
  surfaceOreScoutLegs: 8,
  surfaceOreScoutLegBlocks: 32,
  // Surface ore search + scout legs (owner asked ~200 blocks of search budget).
  thinCoreIronMaxDistance: 96,
  thinCoreOreScoutMaxDistance: 96,
  starterKitGiveDelayMs: 100,
  thinCoreMoveTimeoutMs: 45000,
  ownerPathTimeoutMs: 45000,
  thinCoreCollectTimeoutMs: 240000,
  thinCoreCollectMaxDistance: 48,
  // Prefer finishing the same tree/vein before hopping (one-by-one digs).
  thinCoreCollectOneByOneDefault: true,
  // Movement / sight overhaul defaults
  defaultLiquidCost: 120,
  sightDigRadius: 40,
  sightOreRadius: 96,
  sightScanRadius: 40,
  ownerPathTimeoutMs: 45000,
  lastIncompleteCollectMaxAgeMs: 1200000,
  // Companion play mode (living Player 2 defaults). Still keeps Tier-2 parked.
  playMode: 'companion',
  companionSoftFollow: true,
  companionSoftFollowDistance: 5,
  companionSoftFollowMaxDistance: 18,
  companionSoftFollowCooldownMs: 4000,
  companionTaskNarration: true,
  companionStuckRecovery: true,
  companionAmbientGrounded: true,
  companionLookAtOwner: true,
  companionNarrationCooldownMs: 8000,
  companionAmbientCooldownMs: 150000,
  companionHungerCommentCooldownMs: 90000,
  fleeCooldownMs: 12000,
  fleeChatCooldownMs: 15000,
  ambientAfterOwnerActivityCooldownMs: 45000,
  allowPlannerIdleDecisions: false,
  advancedAutonomyEnabled: false,
  // Curriculum + progression OS removed (archive/removed-for-player2). Flags kept false for old configs.
  curriculumExecutionEnabled: false,
  progressionExecutionEnabled: false,
  curriculumStatusEnabled: false,
  villagerSystemEnabled: false,
  netherSystemEnabled: false,
  blueprintSystemEnabled: false,
  experimentalCombatEnabled: false,
  competentCoreAllowedMacros: [
    'come_here',
    'follow_owner',
    'stay',
    'status_check',
    'get_food',
    'gather_wood',
    'mine_stone',
    'mine_coal',
    'mine_iron',
    'craft_basic_tools',
    'craft_stone_tools',
    'craft_iron_tools',
    'smelt_charcoal',
    'smelt_iron',
    'progress_to_iron',
    'prepare_for_mining',
    'prepare_for_night',
    'return_home',
    'store_items',
    'recover'
  ],
  autonomyMode: 'semi',
  autonomyEnabled: true,
  maxMineArea: 27,
  maxAutonomyDistanceFromOwner: 24,
  followDistance: 3,
  stayNearFriendlyPlayers: true,
  allowCombat: false,
  allowBuilding: true,
  allowNightExploration: false,
  allowChestBreaking: false,
  allowToolUse: true,
  chatCooldownMs: 2500,
  brainTickMs: 8000,
  ollamaDecisionCooldownMs: 30000,
  foodEnabled: true,
  autoEatEnabled: true,
  findFoodEnabled: true,
  cookFoodEnabled: true,
  allowPassiveHunting: true,
  allowFishing: true,
  allowCropHarvesting: false,
  allowFarmReplanting: true,
  maxPassiveHuntSwings: 24,
  maxPassiveHuntKills: 3,
  maxFoodSearchDistance: 32,
  maxFoodDistanceFromOwner: 32,
  minFoodBeforeEating: 18,
  criticalFoodLevel: 8,
  foodSearchCooldownMs: 15000,
  cookFoodCooldownMs: 15000,
  doNotKillNamedMobs: true,
  doNotAttackTamedAnimals: true,
  returnToOwnerAfterFoodTask: true,
  homeBaseEnabled: true,
  baseBuildingEnabled: true,
  storageEnabled: true,
  resourceRunsEnabled: true,
  maxBaseBuildRadius: 12,
  maxStructureWidth: 7,
  maxStructureLength: 7,
  maxStructureHeight: 5,
  maxResourceRunDistance: 48,
  maxResourceRunDurationMs: 180000,
  returnHomeAfterResourceRun: true,
  allowAutonomousBaseMaintenance: true,
  allowAutonomousMining: false,
  allowAutonomousTreeFarming: true,
  allowAutonomousChestUse: true,
  allowBreakingPlayerPlacedBlocks: false,
  allowUsingOwnerChests: false,
  homeLightingEnabled: true,
  homeSleepEnabled: true,
  minimumTorchCount: 8,
  minimumFoodCount: 6,
  minimumLogCount: 16,
  minimumCobblestoneCount: 32,
  minimumCoalCount: 8,
  smartMiningEnabled: true,
  allowOwnerCommandedMining: true,
  allowCaving: false,
  allowDeepMining: false,
  allowDiamondMining: false,
  allowLavaBridging: false,
  allowWaterMining: false,
  allowMiningAtNight: false,
  maxMiningDistanceFromHome: 64,
  maxMiningDistanceFromOwner: 64,
  maxMiningDurationMs: 300000,
  maxBlocksPerMiningTrip: 96,
  maxBranchLength: 24,
  maxBranchCount: 4,
  branchSpacing: 3,
  minTorchCountForMining: 8,
  torchSpacing: 7,
  minFoodForMining: 14,
  minHealthForMining: 14,
  returnHomeWhenInventorySlotsBelow: 5,
  returnHomeWhenToolDurabilityBelow: 20,
  defaultMineYLevel: 48,
  ironMineYLevel: 16,
  diamondMineYLevel: -54,
  coalSearchRadius: 32,
  ironSearchRadius: 32,
  mineEntranceRadiusFromHome: 12,
  requireConfirmationForDeepMining: true,
  requireConfirmationForDiamondMining: true,
  requireConfirmationForCaving: true,
  depositLootAfterMining: true,
  returnToOwnerAfterMining: true,
  farmingEnabled: true,
  animalPensEnabled: true,
  allowAutonomousFarming: true,
  allowAutonomousAnimalCare: false,
  allowAutonomousBreeding: false,
  allowAutonomousHarvesting: true,
  allowAutonomousReplanting: true,
  allowFarmExpansion: false,
  allowAnimalLuring: true,
  allowAnimalBreeding: true,
  allowAnimalSlaughter: false,
  allowShearing: true,
  allowMilking: true,
  allowEggCollection: true,
  maxFarmRadiusFromHome: 16,
  maxFarmSize: 36,
  defaultFarmWidth: 5,
  defaultFarmLength: 5,
  maxAnimalPenRadiusFromHome: 20,
  defaultPenSize: 7,
  maxAnimalsPerPen: 8,
  minWheatSeedsToKeep: 4,
  minWheatToKeep: 6,
  minCarrotsToKeep: 6,
  minPotatoesToKeep: 6,
  minBeetrootsToKeep: 6,
  farmMaintenanceCooldownMs: 30000,
  animalCareCooldownMs: 45000,
  breedingCooldownMs: 300000,
  returnHomeAfterFarmTask: true,
  storeFarmOutputAfterTask: true,
  explorationEnabled: true,
  mapMemoryEnabled: true,
  allowAutonomousExploration: false,
  allowOwnerCommandedExploration: true,
  allowCaveExploration: false,
  allowOceanExploration: false,
  allowEndExploration: false,
  maxExploreRadiusFromHome: 128,
  maxExploreRadiusFromOwner: 96,
  maxExploreDurationMs: 300000,
  maxScoutDistance: 96,
  defaultScoutDistance: 48,
  explorationTickMs: 3000,
  mapSaveIntervalMs: 10000,
  breadcrumbSpacing: 12,
  waypointArrivalDistance: 3,
  avoidKnownDangerZones: true,
  returnHomeAfterExploration: true,
  returnToOwnerAfterExploration: true,
  markDangerZonesAutomatically: true,
  markResourcesAutomatically: true,
  markStructuresAutomatically: true,
  markBiomesAutomatically: true,
  placeExplorationTorches: false,
  minimumFoodForExploration: 14,
  minimumHealthForExploration: 16,
  minimumTorchCountForExploration: 8,
  requireConfirmationForLongExploration: true,
  requireConfirmationForNightExploration: true,
  requireConfirmationForCaveExploration: true,
  requireConfirmationForLeavingHomeRadius: true,
  combatEnabled: true,
  allowCombat: true,
  allowDefensiveCombat: true,
  allowAutonomousCombat: false,
  allowBaseDefense: true,
  allowOwnerDefense: true,
  allowSelfDefense: true,
  allowPvp: false,
  allowAttackingPassiveAnimals: false,
  allowAttackingVillagers: false,
  allowAttackingNamedMobs: false,
  allowAttackingTamedMobs: false,
  allowAttackingBabyMobs: false,
  allowRangedCombat: true,
  allowShieldUse: true,
  allowEmergencyFlee: true,
  allowCombatAtNight: true,
  maxCombatDistanceFromOwner: 32,
  maxCombatDistanceFromHome: 48,
  defendOwnerRadius: 16,
  defendBaseRadius: 24,
  hostileDetectionRadius: 24,
  combatEngageRadius: 12,
  combatDisengageRadius: 20,
  maxHostilesBeforeFlee: 3,
  minHealthToFight: 14,
  criticalHealthToFlee: 8,
  minFoodToFight: 10,
  combatRetreatDistance: 18,
  combatTickMs: 1000,
  combatReportCooldownMs: 5000,
  requireConfirmationForPvp: true,
  requireConfirmationForDangerousCombat: true,
  requireConfirmationForRaidDefense: true,
  returnToOwnerAfterCombat: true,
  returnHomeAfterBaseDefense: true,
  longTermPlanningEnabled: true,
  allowAutonomousGoalPlanning: false,
  allowPlannerToSuggestGoals: true,
  allowSemiAutonomousGoalProgress: true,
  requireOwnerApprovalForNewGoals: true,
  requireOwnerApprovalForRiskySteps: true,
  maxActiveGoals: 3,
  maxGoalSteps: 12,
  maxGoalRunDurationMs: 600000,
  goalStepTimeoutMs: 180000,
  plannerTickMs: 10000,
  plannerDecisionCooldownMs: 45000,
  goalProgressReportCooldownMs: 30000,
  goalSuggestionCooldownMs: 120000,
  autoPauseGoalsAtNight: true,
  autoPauseGoalsWhenOwnerFar: true,
  maxGoalDistanceFromOwner: 96,
  maxGoalDistanceFromHome: 128,
  allowPlannerToUseDiamonds: false,
  allowPlannerToStartDeepMining: false,
  allowPlannerToStartCaving: false,
  allowPlannerToStartNetherTravel: false,
  allowPlannerToStartPvp: false,
  allowPlannerToStartMajorBuilds: false,
  netherPrepEnabled: true,
  netherTravelImplemented: true,
  allowNetherEntry: true,
  allowAutonomousNetherEntry: false,
  allowNetherExploration: false,
  allowNetherMining: false,
  allowFortressSearch: false,
  allowBastionSearch: false,
  allowNetherCombat: false,
  allowPortalBuilding: true,
  allowPortalLighting: true,
  requireConfirmationForNetherEntry: true,
  requireConfirmationForPortalLighting: true,
  requireConfirmationForNetherExploration: true,
  requireConfirmationForNetherMining: true,
  requireConfirmationForFortressSearch: true,
  requireConfirmationForBastionSearch: true,
  maxNetherScoutDistance: 32,
  maxNetherEntryDurationMs: 120000,
  maxDistanceFromNetherPortal: 32,
  netherDangerScanRadius: 32,
  netherPortalSecureRadius: 8,
  returnToPortalWhenUnsafe: true,
  returnToOverworldAfterFirstEntry: true,
  minimumFoodForNether: 16,
  minimumBlockCountForNether: 64,
  minimumTorchCountForNether: 16,
  minimumArrowCountForNether: 16,
  minimumHealthForNether: 18,
  minimumArmorScoreForNether: 8,
  preferGoldBootsForNether: true,
  keepGoldArmorEquippedInNether: true,
  avoidPiglins: true,
  avoidHoglins: true,
  avoidGhasts: true,
  avoidBlazes: true,
  avoidWitherSkeletons: true,
  avoidLavaInNether: true,
  neverUseBedsInNether: true,
  neverPlaceWaterInNether: true,
  lifelikeDialogueEnabled: true,
  dialogueEnabled: true,
  dialogueModel: 'gemma2-2b-local:latest',
  dialogueAudience: 'direct_only',
  respondToAllPlayers: false,
  chatWithFriendlyPlayers: true,
  obeyOnlyOwner: true,
  botAliases: ['tj', 't j', 'teejay', 'tee jay', '@tj', '!tj', 'ai', 'bot'],
  personalityPreset: 'loyal_helper',
  personalityName: 'tj',
  personalityTone: 'friendly, practical, slightly playful, brave but cautious',
  allowBanter: true,
  allowAmbientComments: true,
  allowTaskCommentary: true,
  allowEmotionalFlavor: true,
  allowJokes: true,
  allowSarcasm: false,
  allowRoleplayFlavor: true,
  honestAboutBeingAI: true,
  neverClaimConsciousness: true,
  maxChatResponseLength: 280,
  maxDialogueContextMessages: 10,
  dialogueCooldownMs: 1800,
  ambientCommentCooldownMs: 120000,
  taskCommentCooldownMs: 15000,
  eventCommentCooldownMs: 10000,
  conversationMemoryEnabled: true,
  longTermConversationMemoryEnabled: true,
  maxConversationMemories: 200,
  memorySaveCooldownMs: 10000,
  clearMemoryOnLogout: false,
  clearConversationMemoryOnLogout: false,
  clearVolatileSessionMemoryOnLogout: true,
  allowFullMemoryClearOnLogout: false,
  typoToleranceEnabled: true,
  fuzzyCommandThreshold: 0.72,
  askClarificationThreshold: 0.45,
  naturalCommandRouterEnabled: true,
  naturalCommandExecuteThreshold: 0.85,
  naturalCommandClarifyThreshold: 0.45,
  naturalCommandPendingIntentMs: 30000,
  interactionMode: 'companion',
  askBeforeMediumRisk: true,
  autoRunLowRiskNaturalCommands: true,
  explainFailures: true,
  learnNaturalCommands: true,
  sessionRecorderEnabled: true,
  chatVerbosity: 'normal',
  // Only used when llmMode=full. Off by default so typos do not freeze for 45s.
  llmFallbackForMessyCommands: false,
  llmDialogueTimeoutMs: 25000,
  llmIntentTimeoutMs: 20000,
  ignoreChatLongerThan: 350,
  ignoreRepeatedMessages: true,
  antiSpamEnabled: true,
  promptInjectionDefenseEnabled: true,
  neverRevealSystemPrompts: true,
  neverRevealConfigSecrets: true,
  neverRevealLocalFilePaths: true,
  logLevel: 'info',
  logToFile: true,
  logFile: 'logs/mcai.log',
  maxLogFileSizeMb: 10,
  redactSecrets: true,
  performanceMode: 'balanced',
  maxBlocksScannedPerTick: 5000,
  maxEntitiesScannedPerTick: 200,
  memoryWriteCooldownMs: 5000,
  maxPathfindRetries: 3,
  maxActionRuntimeMs: 180000,
  maxOllamaCallsPerMinute: 6,
  dashboardEnabled: true,
  dashboardHost: '127.0.0.1',
  dashboardPort: 8787,
  dashboardLocalOnly: true,
  dashboardAllowControl: true,
  dashboardAllowDangerousControl: false,
  dashboardRequireOwnerToken: true,
  dashboardToken: 'change-me-local-token',
  dashboardTelemetryIntervalMs: 1000,
  dashboardLogLimit: 200,
  dashboardMemoryReadOnly: true,
  dashboardAllowMemoryExport: true,
  dashboardAllowMemoryReset: false,
  dashboardAllowStopButton: true,
  dashboardAllowSkillRun: true,
  dashboardAllowCurriculumControl: true,
  dashboardAllowGoalControl: true,
  dashboardAllowRawCommand: false,
  progressionEnabled: true,
  minecraftAdvancementTrackingEnabled: true,
  customProgressionTrackingEnabled: true,
  allowProgressionSuggestions: true,
  allowProgressionGoalCreation: true,
  allowProgressionAutoExecution: false,
  requireOwnerApprovalForProgressionGoals: true,
  requireOwnerApprovalForProgressionSteps: true,
  progressionRiskCeiling: 'medium',
  allowProgressionNetherEntry: false,
  allowProgressionEndEntry: false,
  allowProgressionBossFights: false,
  allowProgressionVillagerTrading: false,
  allowProgressionEnchanting: false,
  progressionSuggestionCooldownMs: 120000,
  progressionReportCooldownMs: 30000,
  maxProgressionSuggestions: 5,
  maxProgressionPlanSteps: 12,
  trackVanillaAdvancementsIfAvailable: true,
  fallbackToCustomMilestones: true,
  progressionMemoryFile: 'progression-memory.json',
  gearUpgradesEnabled: true,
  enchantingEnabled: true,
  anvilEnabled: true,
  potionsEnabled: true,
  brewingEnabled: false,
  autoEquipBestGear: true,
  autoSuggestGearUpgrades: true,
  allowAutomaticEnchanting: false,
  allowAutomaticAnvilUse: false,
  allowAutomaticPotionUse: false,
  allowAutomaticBrewing: false,
  requireConfirmationForEnchanting: true,
  requireConfirmationForAnvilUse: true,
  requireConfirmationForBookUse: true,
  requireConfirmationForDiamondGearEnchanting: true,
  requireConfirmationForNetheriteGear: true,
  requireConfirmationForPotionUse: true,
  requireConfirmationForBrewing: true,
  minimumXpLevelsForEnchanting: 3,
  preferredEnchantLevel: 1,
  maxEnchantLevelWithoutConfirmation: 1,
  keepLapisReserve: 3,
  keepIronReserve: 4,
  keepDiamondReserve: 2,
  protectValuableBooks: true,
  protectBestGear: true,
  allowRenamingItems: true,
  allowRepairingGear: true,
  allowCombiningBooks: true,
  allowCombiningGear: true,
  allowUsingMendingGear: true,
  allowNetheriteUpgrade: false,
  gearUpgradeRiskCeiling: 'medium',
  gearUpgradeReportCooldownMs: 30000,
  villagerEconomyEnabled: true,
  villagerTradingEnabled: true,
  allowAutomaticTrading: false,
  allowOwnerApprovedTrading: true,
  requireConfirmationForTrades: true,
  requireConfirmationForEmeraldSpending: true,
  requireConfirmationForRareItemTrading: true,
  requireConfirmationForBookBuying: true,
  requireConfirmationForToolBuying: true,
  requireConfirmationForArmorBuying: true,
  allowVillagerProtection: true,
  allowVillageMemory: true,
  allowVillageLooting: false,
  allowJobSiteManipulation: false,
  allowVillagerTransport: false,
  allowVillagerBreeding: false,
  allowIronGolemCombat: false,
  maxTradeDistanceFromOwner: 64,
  maxTradeDistanceFromHome: 128,
  minEmeraldReserve: 4,
  maxEmeraldsPerTradeWithoutConfirmation: 8,
  maxTradesPerSession: 5,
  tradeSessionTimeoutMs: 120000,
  villagerScanRadius: 32,
  villageMemoryRadius: 96,
  tradeReportCooldownMs: 30000,
  protectNamedVillagers: true,
  protectVillagersFromCombat: true,
  avoidIronGolems: true,
  blueprintBuildingEnabled: true,
  schematicImportEnabled: false,
  allowImportedSchematics: false,
  allowAutomaticBuilding: false,
  allowOwnerApprovedBuilding: true,
  requireConfirmationForBlueprintBuild: true,
  requireConfirmationForAreaClearing: true,
  requireConfirmationForImportedSchematic: true,
  requireConfirmationForLargeBuild: true,
  maxBlueprintBlocks: 256,
  maxBlueprintWidth: 16,
  maxBlueprintLength: 16,
  maxBlueprintHeight: 8,
  maxBuildDistanceFromOwner: 64,
  maxBuildDistanceFromHome: 96,
  maxBlocksPlacedPerRun: 64,
  blueprintBuildTickMs: 500,
  blueprintPlacementDelayMs: 150,
  allowAreaClearing: false,
  allowBreakingBlocksForBuild: false,
  allowReplacingBlocks: false,
  allowBuildingNearLava: false,
  allowBuildingInWater: false,
  allowDangerousBlocksInBlueprints: false,
  allowTntInBlueprints: false,
  allowFireInBlueprints: false,
  allowLavaInBlueprints: false,
  blueprintMemoryFile: 'blueprint-memory.json',
  serverPluginBridgeEnabled: true,
  serverPluginBridgeMode: 'local_http',
  serverPluginHost: '127.0.0.1',
  serverPluginPort: 8791,
  serverPluginLocalOnly: true,
  serverPluginRequireToken: true,
  serverPluginToken: 'change-me-server-bridge-token',
  serverPluginAllowControl: true,
  serverPluginAllowDangerousControl: false,
  serverPluginReadOnlyByDefault: true,
  serverPluginExposeEvents: true,
  serverPluginExposeTelemetry: true,
  serverPluginExposeProtectedZones: true,
  serverPluginExposeAdvancements: true,
  serverPluginExposeDeathEvents: true,
  serverPluginExposeRegionRegistry: true,
  serverPluginAllowEmergencyStop: true,
  serverPluginAllowServerCommands: false,
  serverPluginAllowTeleport: false,
  serverPluginAllowGiveItems: false,
  serverPluginAllowWorldEdit: false,
  serverPluginAllowOperatorActions: false,
  serverPluginEventBufferSize: 500,
  serverPluginPollIntervalMs: 1000,
  serverPluginTimeoutMs: 5000
};

export function loadConfig() {
  let fileConfig = {};

  if (fs.existsSync(configPath)) {
    let text = fs.readFileSync(configPath, 'utf8');
    if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
    fileConfig = JSON.parse(text);
  }

  const config = { ...defaults, ...fileConfig };
  config.friendlyPlayers = Array.isArray(config.friendlyPlayers) && config.friendlyPlayers.length > 0
    ? config.friendlyPlayers
    : [config.ownerUsername];
  // Keep playMode / interactionMode aligned when only one is set in config.json.
  if (fileConfig.playMode && !fileConfig.interactionMode) config.interactionMode = fileConfig.playMode;
  if (fileConfig.interactionMode && !fileConfig.playMode) config.playMode = fileConfig.interactionMode;
  if (config.playMode === 'companion' || config.interactionMode === 'companion') {
    config.companionSoftFollow = config.companionSoftFollow !== false;
    config.companionTaskNarration = config.companionTaskNarration !== false;
    config.companionStuckRecovery = config.companionStuckRecovery !== false;
    config.companionAmbientGrounded = config.companionAmbientGrounded !== false;
    config.companionLookAtOwner = config.companionLookAtOwner !== false;
    config.allowAmbientComments = config.allowAmbientComments !== false;
    config.allowTaskCommentary = config.allowTaskCommentary !== false;
    config.lifelikeDialogueEnabled = config.lifelikeDialogueEnabled !== false;
  }
  // Progression acceptance mode: never auto-kit; always allow surface ore scout.
  if (config.progressionTestMode === true) {
    config.starterKitEnabled = false;
    config.starterKitOnSpawn = false;
    config.surfaceOreScoutEnabled = true;
    config.llmFallbackForMessyCommands = false;
    if (!config.llmMode || config.llmMode === 'full') config.llmMode = 'dialogue';
  }
  config.projectRoot = projectRoot;
  config.configPath = configPath;
  config.memoryPath = path.join(projectRoot, 'memory.json');
  return config;
}

export { configPath, projectRoot };
